<a href="https://colab.research.google.com/github/YE-JIN-LEE/DALC_Scala/blob/main/DALC_scalar4_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%8D%B0%EC%9D%B4%ED%84%B0_%ED%83%80%EC%9E%85%EA%B3%BC_numpy%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0__.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초

## 넘파이 패키지 불러오기

In [1]:
# 넘파이 패키지를 불러오기 np로 줄여쓰기# 넘파이 패키지를 불러오기 np로 줄여쓰기

import numpy as np

## array 정의 및 생성

In [3]:
# 넘파이 array를 사용하여 a라는 변수에 1부터 10까지의 숫자 리스트 배열을 생성하기

data = [1,2,3,4,5,6,7,8,9,10]
a = np.array(data)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#파이썬의 기본 range 함수와 비슷한 넘파이 range 함수를 사용하여 ndarray를 만들 수 있습니다:

aa = np.array([range(i, i+3) for i in data])
aa

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12]])

## 배열 구성

In [5]:
# full 함수를 사용하여 b라는 변수에 2.71 수로 3 X 4 다차원 배열 만들기

b = np.full((3,4), 2.71)
b

array([[2.71, 2.71, 2.71, 2.71],
       [2.71, 2.71, 2.71, 2.71],
       [2.71, 2.71, 2.71, 2.71]])

In [6]:
# arrange 함수를 사용하여 c라는 변수에 0부터 10까지 짝수만 있는 배열 구성하기

c = np.arange(0, 10, 2)
c

array([0, 2, 4, 6, 8])

In [8]:
# linespace 함수를 사용하여 d라는 변수에 0부터 1까지 4개 요소 값을 가진 배열 생성하기

d = np.linspace(0,1,4)
d

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [9]:
# randint 함수를 사용하여 0 부터 100까지 수를 2 X 2 배열로 생성하기

e = np.random.randint(0,100, (2,2))
e

array([[ 8, 87],
       [75, 18]])

## 배열 인덱싱

In [10]:
# a변수에서 인덱스 2 (앞에서 3번째) 와 인덱스 -3 (뒤에서 3번째)에 해당하는 수 가져오기

print(a[2], a[-3])

3 8


In [12]:
# a 변수에서 인덱스 3부터 9 까지 슬라이싱하기
print(a[3:9])

[4 5 6 7 8 9]


## 배열 재구조화

In [14]:
#차원의 개수 알아보는 함수

print(a.ndim)

1


In [15]:
#차원의 크기 알아보는 함수

print(a.shape)

(10,)


In [16]:
#전체 배열크기 알아보는 함수

print(a.size)

10


In [17]:
#0부터10까지 정수를 가진 x변수에서 4~7까지의 요소를 가진 하위배열생성

x = np.arange(10)
x[4:7]

array([4, 5, 6])

In [18]:
#0부터10까지 정수를 가진 x변수에서 첫번째 다섯 요소를 가진 하위 배열 생성

x[:5]

array([0, 1, 2, 3, 4])

In [19]:
#0부터10까지 정수를 가진 x변수에서 인덱스 5 이후의 요소를 가진 하위 배열을 생성

x[5:]

array([5, 6, 7, 8, 9])

In [20]:
# 인덱스 0,1행과 인덱스 0,1,2열 즉 2행3열인 다차원 하위 배열 생성(콤마이용하기)

z = np.array([[2,4,6,8], [3,6,9,12], [4,8,12,16]])
z[:2, :3]

array([[2, 4, 6],
       [3, 6, 9]])

In [21]:
#1부터 10까지 배열을 3행3열로 재배열하기(reshape사용)

zz = np.arange(1,10).reshape(3,3)
zz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 배열 결합

In [22]:
#두개의 배열 결합하기

zzz = np.concatenate([a,c])
zzz

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  2,  4,  6,  8])

In [28]:
#수직으로 두개의 배열 결합하기
xx = np.array([1,2,3])
grid = np.array([[4,5,6],[7,8,9]])
v = np.vstack([xx, grid])
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
#수평으로 두개의 배열 결합하기
y = np.array([[99], [99]])
z = np.hstack([grid,y])
z

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

## 배열 분할

In [34]:
#7개의 숫자를 가진 리스트 x를 3개의 변수 x1,x2,x3로 분할하기

ss = [1,2,3,77,77,3,2,1]
x1, x2, x3 = np.split(ss,[3,5])
print(x1, x2, x3)

[1 2 3] [77 77] [3 2 1]


In [35]:
#4행4열 차원을 배열이 상하 2개로 나누게 분할
gg = np.arange(16).reshape((4,4))
upper, lower=np.vsplit(gg, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


# Numpy 심화

## 유니버셜함수

In [55]:
# zeros 함수는 0으로 채워진 배열을 만듭니다:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [56]:
#2D 배열(즉, 행렬)을 만들려면 원하는 행과 열의 크기를 튜플로 전달합니다. 예를 들어 다음은 3 \times 4 크기의 행렬입니다:

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
a.shape

(3, 4)

In [59]:
a.ndim # len(a.shape)와 같습니다

2

In [60]:
a.size

12

In [61]:
# 초기화되지 않은 2 \times 3 크기의 배열을 만듭니다(배열의 내용은 예측이 불가능하며 메모리 상황에 따라 달라집니다):

np.empty((2,3))

array([[2.0e-323, 2.5e-323, 3.0e-323],
       [3.5e-323, 4.0e-323, 4.4e-323]])

In [62]:
#array 함수는 파이썬 리스트를 사용하여 ndarray를 초기화합니다:

np.array([[1,2,3,4], [10, 20, 30, 40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [63]:
x = np.array([-10, -5, 0, 3, 7])
# x에 있는 배열을 모두 양의 정수로 반환하기

np.abs(x)

array([10,  5,  0,  3,  7])

In [64]:
# 모두 양의 정수가 된 배열 x를 자연로그 배열로 반환하기

bbb = np.abs(x)
np.log(bbb)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


array([2.30258509, 1.60943791,       -inf, 1.09861229, 1.94591015])

## 집계함수

In [65]:
x=np.array([-2,-1,0,1,2])
"절댓값을 씌우려면?"
힌트: "np.absolute(x)"

np.abs(x)

array([2, 1, 0, 1, 2])

In [66]:
#삼각함수
theta = np.linspace(0,np.pi,3)
print("theta=" , theta)
print("코사인 함수 =", np.cos(theta))
print("탄젠트 함수= ", np.tan(theta)) 



theta= [0.         1.57079633 3.14159265]
코사인 함수 = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
탄젠트 함수=  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [91]:
#역삼각함수
x = [-1,0,1]
print("역 사인함수=", np.arcsin(x))
print("역 코사인함수=",np.arccos(x))
print("역 탄젠트함수=",np.arctan(x))

역 사인함수= [-1.57079633  0.          1.57079633]
역 코사인함수= [3.14159265 1.57079633 0.        ]
역 탄젠트함수= [-0.78539816  0.          0.78539816]


In [92]:
#로그함수
x=[1,2,4,10]
print("자연로그=", np.log(x))
print("밑이2인 로그함수=", np.log2(x))
print("밑이 10인 로그함수=", np.log10(x))

자연로그= [0.         0.69314718 1.38629436 2.30258509]
밑이2인 로그함수= [0.         1.         2.         3.32192809]
밑이 10인 로그함수= [0.         0.30103    0.60205999 1.        ]


In [93]:
#지수함수
x=[1,2,3]
print("e^x=", np.exp(x))
print("2^x", np.exp2(x))
print("3^x=", np.power(3,x))

e^x= [ 2.71828183  7.3890561  20.08553692]
2^x [2. 4. 8.]
3^x= [ 3  9 27]


In [94]:
#out 인자 
x=np.arange(5)
y=np.empty(5)
np.multiply(x,10,out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [95]:
#out 인자를 활용하여 배열 슬라이싱
x=np.arange(5)
y=np.empty(10)
np.power(2,x,out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [96]:
#reduce 함수
x=np.arange(1,5)
np.add.reduce(x)

10

In [97]:
#sum,max,min함수
s=np.random.random(1000)
print("s의최솟값=",np.min(s))
print("s의최댓값=",np.max(s))


s의최솟값= 0.002061153603725052
s의최댓값= 0.9988512679756393


In [74]:
#axis 인자
"axis=0: 열기준 집계연산"
"axis=1: 행기준 집계연산"
"axis=none: 배열 내 모든 요소의 집계연산axis 인자"

'axis=none: 배열 내 모든 요소의 집계연산axis 인자'

In [75]:
m= np.random.random((3,4))
print(m)

[[0.47713352 0.51264547 0.05493704 0.52376519]
 [0.67126738 0.94062144 0.68142494 0.84832423]
 [0.07015884 0.76213502 0.17959271 0.78462517]]


## 브로드캐스팅 연산

In [98]:
# 크기가 같은 어레이의 연산을 하기

x = np.array([0,1,2])
y = np.array([3,3,3])
x+y

array([3, 4, 5])

In [99]:
# 배열의 크기를 늘려서 연산하기

x = np.array([0,1,2])
x+10

array([10, 11, 12])

## 비교연산자

In [100]:
# any 함수를 이용하여 하나라도 만족하면 true를 산출하는 코드만들기

x = np.arange(10)
np.any(x<5), np.any(x<0)

(True, False)

In [101]:
# all함수를 이용하여 true산출 코드 만들기

x = np.arange(10)
np.all(x<5), np.all(x<0)

(False, False)

In [102]:
# 1~5사이의 구간에서 5개 정수를 무작위로 발생시켜 1차원배열 2개변수를 생성하고 이에대한 불리언 값 결과내기

a = np.random.randint(1,5,5)
b = np.random.randint(1,5,5)
print(a,b)
a==b

[3 4 1 4 4] [2 3 4 2 3]


array([False, False, False, False, False])

## 팬시 인덱싱

In [103]:
#배열을 생성하여 인덱싱하기

a = np.arange(10)
b = np.array([3,6,9])
a[b]

array([3, 6, 9])

In [106]:
#인덱스 값을 가진 2차원 배열(예를 들어 row=np.array([0,1,2]))을 이용하여 인덱싱

x = np.arange(12).reshape((3,4))
x

row = np.array([0,1,2])
col = np.array([2,1,3])
x [row, col]

array([ 2,  5, 11])

## 정렬 

In [107]:
#np.sort함수를 이용하여 복사하기

x = np.array([4,1,5,2,3])
print(x, np.sort(x))

[4 1 5 2 3] [1 2 3 4 5]


In [108]:
#변수.sort함수를 이용하여 정렬하기

x.sort()
print(x)

[1 2 3 4 5]


In [109]:
#np.arsort함수 이용하여 정렬 요소의 인덱스를 반환하기
i = np.argsort(x)
print(i)

[0 1 2 3 4]


In [112]:
#x_reverse를 이용하여 내림차순

x_reverse = np.sort(x)[::-1]
print(x_reverse)

[5 4 3 2 1]


In [114]:
#axis를 이용하여 각 열을 기준으로 정렬하기

x = np.array([[2,0,6], [7,3,4], [1,5,3]])
np.sort(x, axis = 0)

array([[1, 0, 3],
       [2, 3, 4],
       [7, 5, 6]])

In [115]:
#axis를 이용하여 각 행을 기준으로 정렬하기#axis를 이용하여 각 행을 기준으로 정렬하기

x = np.array([[2,0,6], [7,3,4], [1,5,3]])
np.sort(x, axis = 1)

array([[0, 2, 6],
       [3, 4, 7],
       [1, 3, 5]])