# 1.빅데이터 분석 및 처리

## 빅데이터
- 관계형 데이터베이스 관리 시스템(RDBMS; Relational Database Management Systems)과 같은
  전통적 데이터 관리 기법으로 다루기 힘든 데이터
  
## R
- 통계 계산과 그래픽을 위한 프로그래밍 언어이자 소프트웨어 환경
- 다양한 통계 기법과 수치 해석 기법 지원

## python
- 이해하기 쉽고 유연한 문법
- 연산능력을 극대화 시켜주는 오프소스 라이브러리(모듈)가 풍부
- 대용량 데이터 세트의 분석과 처리에 유연성을 가짐
- 다양한 패키지가 목적에 맞게 개발

  ### Numpy : 동일한 데이터 타입을 가진 배열 기반의 데이터 처리
  ### Pandas : data frame 형태로 데이터를 다룸
  ### Scipy : 과학 계산 작업
  ### Mataplotib : 데이터 시각화
  ### Scikit-Learn : 머신러닝
      

# 2.데이터 저장 및 가공

## 데이터 분석
- 숫자 배열을 효율적으로 저장하고 가공하는 것은 빅데이터 분석을 위한 기본 절차
- 숫자 배열을 전문적으로 다루는 Numpy 패키지 필요

# 3.Numpy 패키지

## 넘파이(Numerical Python)
- 벡터 및 행렬 연산에 유용한 기능 제공
- 빅데이터 분석을 위해 사용되는 라이브러리
- pandas와 matplotlib에서 기본으로 사용되는 패키지

- arry(:동일한 데이터 타입을 갖는 벡터나 행렬) 단위로 데이터 관리 및 연산 수행
- 배열 규모가 커질수록 데이터 자장 및 처리에 효율적

# 4.행렬 생성

In [1]:
import numpy as np

data1 = [1,2,3,4,5]
data2 = [6,5,4,3,2,1]
print(data1, data2)

[1, 2, 3, 4, 5] [6, 5, 4, 3, 2, 1]


In [2]:
ar1 = np.array(data1)
ar1

array([1, 2, 3, 4, 5])

In [5]:
ar2 = np.array(data1, dtype = 'float')
ar2

array([1., 2., 3., 4., 5.])

In [6]:
ar3 = np.array([range(i, i+3) for i in data1])
ar3

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [7]:
ar4 = np.full((3,5),3.14)
ar4

# full함수 ((행렬 크기), 지정 값)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
ar5 = np.arange(0, 20, 2)
ar5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
ar6 = np.linspace(0, 1, 3)
ar6

# 0.5 간격의 3개 요소 값을 가진 배열 생성

array([0. , 0.5, 1. ])

In [11]:
ar7 = np.random.random((3,3))
ar7

# 3x3 행렬을 생성하고, 0과 1 사이의 무작위 값으로 채움

array([[0.24952148, 0.68224458, 0.17152422],
       [0.7461682 , 0.14056411, 0.52385612],
       [0.41925453, 0.03431664, 0.64183744]])

In [12]:
ar8 = np.random.randint(0, 100, (3,3))
ar8

# 0과 100 사이, (구간의 시작, 구간의 끝)
# (3,3)은 3x3 배열크기

array([[ 0, 86, 29],
       [42, 84, 79],
       [62, 81, 74]])

In [13]:
ar9 = np.eye(3)
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 5.배열 분할, 재구성, 결합

In [15]:
x = np.random.randint(10, size=(3,4,5))
x

array([[[5, 7, 3, 6, 1],
        [6, 5, 5, 8, 1],
        [4, 6, 3, 5, 7],
        [1, 7, 9, 6, 2]],

       [[7, 8, 6, 3, 0],
        [2, 1, 4, 4, 6],
        [0, 6, 9, 8, 6],
        [7, 9, 9, 4, 6]],

       [[2, 8, 1, 7, 3],
        [1, 9, 8, 1, 4],
        [8, 6, 0, 5, 6],
        [9, 0, 8, 1, 4]]])

In [16]:
print("x ndim:", x.ndim) # 차원의 개수
print("x shape:", x.shape) # 차원의 크기
print("x size:", x.size) # 전체 배열 크기

x ndim: 3
x shape: (3, 4, 5)
x size: 60


In [17]:
y = np.array([2,4,6,8,10])
print(y[0], y[-2])

2 8


In [19]:
z = np.array([[2,4,6,8,10], [3,6,9,12,15]])
print(z[1,0])

3


In [20]:
z[0,0] = 12
z

array([[12,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15]])